# Generated by Django 5.2.8 on 2026-03-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_mensagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacinacao',
            name='data_proxima',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
