# Generated by Django 5.2.8 on 2026-03-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_mensagem', '0002_alter_vacinacao_data_proxima'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacinacao',
            name='lembrete_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
