# Generated by Django 5.2.8 on 2026-03-25 15:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_mensagem', '0003_vacinacao_lembrete_enviado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('emojis', models.CharField(max_length=5)),
            ],
        ),
        migrations.RenameField(
            model_name='vacinacao',
            old_name='lembrete_enviado',
            new_name='notificado',
        ),
        migrations.AddField(
            model_name='dono',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dono',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacinacao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacinacao',
            name='data_notificacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_mensagem.especie'),
        ),
    ]
