# Generated by Django 5.2.8 on 2026-03-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_mensagem', '0004_especie_rename_lembrete_enviado_vacinacao_notificado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacinacao',
            old_name='data_notificacao',
            new_name='data_notificacao_1_dia',
        ),
        migrations.RenameField(
            model_name='vacinacao',
            old_name='notificado',
            new_name='notificado_1_dia',
        ),
        migrations.AddField(
            model_name='vacinacao',
            name='data_notificacao_3_dias',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacinacao',
            name='notificado_3_dias',
            field=models.BooleanField(default=False),
        ),
    ]
