# Generated by Django 5.2.8 on 2026-04-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_mensagem', '0005_rename_data_notificacao_vacinacao_data_notificacao_1_dia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacinacao',
            name='vacinado',
            field=models.BooleanField(default=False),
        ),
    ]
